const NewsArticle = require("../Models/NewsArticle");
const User = require("../Models/user.model");
const { triggerAllSocialMedia } = require("./socialTriggerService");

// Cache for authors to avoid constant DB lookups
let authorCache = null;

const EMAILS = {
    SNEHA: "snehakumari83832@gmail.com",
    ENTERTAINMENT: "entertainment@gmail.com",
    SPORTS: "sports@gmail.com",
    LIFESTYLE: "lifesyle@gmail.com" // Matches user's typo 'lifesyle'
};

/**
 * Initialize author cache by fetching users from DB
 */
const initAuthors = async () => {
    try {
        const users = await User.find({ email: { $in: Object.values(EMAILS) } });
        const cache = {};
        users.forEach(u => {
            cache[u.email] = { id: u._id, name: u.name };
        });
        authorCache = cache;
        console.log("✅ Auto-Pilot Authors Initialized:", Object.keys(authorCache).length);
    } catch (err) {
        console.error("❌ Failed to initialize authors:", err.message);
    }
};

/**
 * Get Author based on Category
 */
const getAuthorForCategory = (category) => {
    if (!authorCache) return { name: "Prime Time News", id: null };
    
    let email = EMAILS.SNEHA; // Default
    const cat = (category || "").toLowerCase();

    if (cat.includes("entertainment")) email = EMAILS.ENTERTAINMENT;
    else if (cat.includes("sports") || cat.includes("cricket")) email = EMAILS.SPORTS;
    else if (cat.includes("lifestyle") || cat.includes("health")) email = EMAILS.LIFESTYLE;

    return authorCache[email] || { name: "Prime Time News", id: null };
};

/**
 * Automatically publish a balanced batch of pending HI and EN drafts
 * Skips restricted sources (BBC, ABP) and finds the next valid one.
 */
const publishPendingDrafts = async () => {
    if (!authorCache) await initAuthors();

    try {
        let processed = 0;
        const RESTRICTED_SOURCES = ["times of india", "toi", "abp"]; // ABP blocked for safety as per user request

        const languages = ["hi", "en"];
        for (const lang of languages) {
            // Find up to 10 oldest drafts for this language to search for a valid one
            const potentialDrafts = await NewsArticle.find({ 
                autoGenerated: true, 
                status: "draft", 
                lang: lang 
            }).sort({ createdAt: 1 }).limit(100);

            for (const draft of potentialDrafts) {
                const sourceName = (draft.source || "").toLowerCase();
                const isRestricted = RESTRICTED_SOURCES.some(src => sourceName.includes(src));

                if (isRestricted) {
                    console.log(`[AutoPost] ⏩ Skipping restricted source (${lang.toUpperCase()}): "${draft.title}" (${draft.source})`);
                    continue; // Check next draft in the list
                }

                // If not restricted, publish this one
                const author = getAuthorForCategory(draft.category);
                
                // Add Branding
                const branding = " - Prime Time News";
                if (!draft.title.includes(branding)) {
                    draft.title = `${draft.title}${branding}`;
                    draft.slug = draft.title.toLowerCase().trim().replace(/[\s_]+/g, "-").replace(/[^\u0900-\u097Fa-z0-9\u0915-\u0939\u0941-\u094d-]+/g, "").replace(/-+/g, "-").replace(/(^-|-$)+/g, "");
                }

                draft.status = "published";
                draft.author = author.name;
                draft.authorId = author.id;
                draft.publishedAt = new Date();
                draft.isHidden = false;
                draft.isLatest = true;
                draft.isTrending = true;

                await draft.save();
                processed++;
                console.log(`[AutoPost] ✅ Published (${lang.toUpperCase()}): "${draft.title}" under author: ${author.name}`);
                
                // Trigger ALL Social Media and Notifications
                triggerAllSocialMedia(draft).catch(err => console.error("[AutoPost] ❌ Social Trigger Failed:", err.message));
                
                break; // Stop looking for this language once one is published
            }
        }

        return { processed, msg: `Successfully processed cycle. ${processed} drafts now live.` };
    } catch (err) {
        console.error("❌ Auto-Publish Drafts Error:", err.message);
        throw err;
    }
};

module.exports = { publishPendingDrafts };
