const AppConfig = require("../Models/AppConfig");
const User = require("../Models/user.model");
const facebookService = require("./facebookService");
const linkedinService = require("./linkedinService");
const twitterService = require("./twitterService");
const onesignalService = require("./onesignalService");
const imageService = require("./imageService");
const { getArticleUrl } = require("../utils/articleUtils");

/**
 * Trigger Facebook auto-post when an article is published.
 */
async function triggerFacebookPost(newsItem) {
  try {
    let pageId, pageAccessToken;

    const globalConfig = await AppConfig.findOne({ key: "facebook" });
    if (globalConfig?.facebook?.pageId && globalConfig?.facebook?.autoPostEnabled) {
      pageId = globalConfig.facebook.pageId;
      pageAccessToken = globalConfig.facebook.pageAccessToken;
    } else if (newsItem.authorId) {
      const user = await User.findById(newsItem.authorId);
      if (user?.facebook?.pageId) {
        pageId = user.facebook.pageId;
        pageAccessToken = user.facebook.pageAccessToken;
      }
    }

    if (!pageId || !pageAccessToken) return;

    const articleUrl = getArticleUrl(newsItem);
    const message = `📰 ${newsItem.title}\n\n${newsItem.summary || ""}`;
    
    let finalImageData = newsItem.image || null;
    
    // SMART BRANDING: Avoid double-branding auto-generated news (they are already branded during scraping)
    const isAlreadyBranded = newsItem.autoGenerated === true && (finalImageData || "").includes("cloudinary");

    if (!isAlreadyBranded && finalImageData && typeof finalImageData === "string" && finalImageData.startsWith("http")) {
      console.log(`[Trigger] 🎨 Branding image for Facebook: ${newsItem.title}`);
      const brandedBuffer = await imageService.brandImageWithTitle(finalImageData, newsItem.title);
      if (brandedBuffer) {
        finalImageData = brandedBuffer;
      }
    } else if (isAlreadyBranded) {
      console.log(`[Trigger] ⏩ Skipping re-branding (already processed): ${newsItem.title}`);
    }

    await facebookService.postToPage(pageId, pageAccessToken, message, articleUrl, finalImageData);
  } catch (error) {
    console.error("[Trigger] Facebook Error:", error.message);
  }
}

/**
 * Trigger LinkedIn auto-post to ALL connected accounts.
 */
async function triggerLinkedInPost(newsItem) {
  try {
    const config = await AppConfig.findOne({ key: "linkedin-multi" });
    const accounts = (config?.linkedinAccounts || []).filter(a => a.autoPostEnabled && a.accessToken);
    if (accounts.length === 0) return;

    const articleUrl = getArticleUrl(newsItem);
    const message = `📰 ${newsItem.title}\n\n${newsItem.summary || ""}\n\nRead more 👇`;

    const results = await Promise.allSettled(
      accounts.map(a => linkedinService.postToLinkedIn(a.accessToken, a.accountId, message, articleUrl, newsItem.image || null))
    );
    results.forEach((r, i) => {
      if (r.status === "fulfilled") console.log(`[Trigger] LinkedIn ✅ Posted to: ${accounts[i].accountName}`);
      else console.error(`[Trigger] LinkedIn ❌ Failed for ${accounts[i].accountName}:`, r.reason?.message);
    });
  } catch (error) {
    console.error("[Trigger] LinkedIn Error:", error.message);
  }
}

/**
 * Trigger Twitter auto-post.
 */
async function triggerTwitterPost(newsItem) {
  try {
    let credentials = {};

    const globalConfig = await AppConfig.findOne({ key: "twitter" });
    if (globalConfig?.twitter?.accessToken && globalConfig?.twitter?.autoPostEnabled) {
      credentials = {
        appKey: globalConfig.twitter.appKey,
        appSecret: globalConfig.twitter.appSecret,
        accessToken: globalConfig.twitter.accessToken,
        accessSecret: globalConfig.twitter.accessSecret,
      };
    } else if (newsItem.authorId) {
      const user = await User.findById(newsItem.authorId);
      if (user?.twitter?.accessToken) {
        credentials = {
          appKey: user.twitter.appKey,
          appSecret: user.twitter.appSecret,
          accessToken: user.twitter.accessToken,
          accessSecret: user.twitter.accessSecret,
        };
      }
    }

    if (!credentials.accessToken) return;

    const articleUrl = getArticleUrl(newsItem);
    const message = `📰 ${newsItem.title}`;

    await twitterService.postToTwitter(credentials, message, articleUrl);
  } catch (error) {
    console.error("[Trigger] Twitter Error:", error.message);
  }
}

/**
 * Trigger OneSignal Notification.
 */
async function triggerOneSignal(newsItem) {
  try {
    await onesignalService.sendNotification(newsItem);
  } catch (error) {
    console.error("[Trigger] OneSignal Error:", error.message);
  }
}

/**
 * Master function to trigger ALL social media and notifications.
 */
async function triggerAllSocialMedia(newsItem) {
  if (newsItem.status !== "published") return;
  
  console.log(`[Trigger] 🚀 Triggering social media for: ${newsItem.title}`);
  
  // Run in parallel for speed
  await Promise.allSettled([
    triggerFacebookPost(newsItem),
    triggerLinkedInPost(newsItem),
    triggerTwitterPost(newsItem),
    triggerOneSignal(newsItem)
  ]);
}

module.exports = {
  triggerFacebookPost,
  triggerLinkedInPost,
  triggerTwitterPost,
  triggerOneSignal,
  triggerAllSocialMedia
};
