const mongoose = require("mongoose");
const dotenv = require("dotenv");
const path = require("path");

dotenv.config({ path: path.join(__dirname, "backend", ".env") });

async function checkDrafts() {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        const NewsArticle = mongoose.model("NewsArticle", new mongoose.Schema({}, { strict: false }));
        
        const count = await NewsArticle.countDocuments({ autoGenerated: true, status: "draft" });
        const latest = await NewsArticle.find({ autoGenerated: true, status: "draft" })
            .sort({ createdAt: -1 })
            .limit(5)
            .select("title createdAt lang");

        console.log(`Total AI Drafts: ${count}`);
        console.log("Latest AI Drafts:");
        latest.forEach(d => console.log(`- [${d.lang}] ${d.title} (${d.createdAt})`));

        await mongoose.connection.close();
    } catch (err) {
        console.error(err);
    }
}

checkDrafts();
