const express = require("express");
const { autoGenerateNews, fetchAndProcessNews, getAutoGeneratedDrafts } = require("../Controllers/autoNewsController");

const router = express.Router();

router.post("/auto-news", autoGenerateNews);        // Manual Trigger
router.get("/auto-news/fetch-daily", fetchAndProcessNews); // Batch Trigger
router.get("/auto-news/drafts", getAutoGeneratedDrafts); // Get Drafts


module.exports = router;
