const express = require("express");
const { autoGenerateNews, fetchAndProcessNews, getAutoGeneratedDrafts, cleanupDuplicates, fixLanguageTags } = require("../Controllers/autoNewsController");

const router = express.Router();

router.get("/auto-news/ping", (req, res) => res.json({ success: true, msg: "AI News Service is Reachable!", port: process.env.PORT }));
router.post("/auto-news", autoGenerateNews);        // Manual Trigger
router.get("/auto-news/fetch-daily", fetchAndProcessNews); // Batch Trigger
router.get("/auto-news/drafts", getAutoGeneratedDrafts); // Get Drafts
router.get("/auto-news/cleanup", cleanupDuplicates); // Cleanup Duplicates (Removed duplicates)
router.get("/auto-news/fix-languages", fixLanguageTags); // Fix lang tags (Existing data cleanup)


module.exports = router;
