const express = require("express");
const { autoGenerateNews, fetchAndProcessNews, getAutoGeneratedDrafts, cleanupDuplicates } = require("../Controllers/autoNewsController");

const router = express.Router();

router.post("/auto-news", autoGenerateNews);        // Manual Trigger
router.get("/auto-news/fetch-daily", fetchAndProcessNews); // Batch Trigger
router.get("/auto-news/drafts", getAutoGeneratedDrafts); // Get Drafts
router.get("/auto-news/cleanup", cleanupDuplicates); // Cleanup Duplicates


module.exports = router;
