const mongoose = require("mongoose");
const dotenv = require("dotenv");
const NewsArticle = require("../Models/NewsArticle");
const NewsConfig = require("../Models/news.model");

dotenv.config({ path: ".env" });

const migrate = async () => {
    try {
        console.log("Connecting to DB...");
        await mongoose.connect(process.env.MONGO_URL);
        console.log("Connected to DB successfully.");

        // Fetch all legacy configs
        const configs = await NewsConfig.find({});
        console.log(`Found ${configs.length} NewsConfig documents.`);

        const categories = [
            "india",
            "sports",
            "business",
            "technology",
            "entertainment",
            "lifestyle",
            "world",
            "health",
            "awards"
        ];

        let totalMigrated = 0;
        let totalSkipped = 0;
        const seenSlugs = new Set();

        for (const config of configs) {
            for (const category of categories) {
                const items = config[category] || [];

                for (const item of items) {
                    try {
                        if (!item.slug || seenSlugs.has(item.slug)) {
                            totalSkipped++;
                            continue;
                        }

                        // Map legacy item to new model
                        const newArticle = new NewsArticle({
                            title: item.title,
                            slug: item.slug,
                            category: item.category || category,
                            subCategory: item.subCategory,
                            summary: item.summary,
                            content: item.content,
                            image: item.image,
                            tags: item.tags,
                            isLatest: item.isLatest,
                            isTrending: item.isTrending,
                            isHidden: item.isHidden,
                            targetLink: item.targetLink,
                            nominationLink: item.nominationLink,
                            author: item.author,
                            status: item.status,
                            autoGenerated: item.autoGenerated,
                            source: item.source,
                            publishedAt: item.createdAt || config.createdAt
                        });

                        await newArticle.save();
                        seenSlugs.add(item.slug);
                        totalMigrated++;
                        if (totalMigrated % 100 === 0) {
                            console.log(`Migrated ${totalMigrated} items...`);
                        }
                    } catch (itemErr) {
                        // If it fails due to Duplicate Key (Mongoose unique index), catch it here too
                        if (itemErr.code === 11000) {
                            seenSlugs.add(item.slug);
                            totalSkipped++;
                        } else {
                            console.error(`Error migrating item: ${item.title}`, itemErr.message);
                            totalSkipped++;
                        }
                    }
                }
            }
        }

        console.log("------------------------------------------");
        console.log(`Migration Complete!`);
        console.log(`Total Migrated: ${totalMigrated}`);
        console.log(`Total Skipped/Duplicates: ${totalSkipped}`);
        console.log("------------------------------------------");

        process.exit(0);
    } catch (error) {
        console.error("Migration failed:", error);
        process.exit(1);
    }
};

migrate();
