const mongoose = require("mongoose");

const newsArticleSchema = new mongoose.Schema(
    {
        title: {
            type: String,
            required: true,
            trim: true,
            minlength: 5,
            maxlength: 300,
        },
        slug: {
            type: String,
            required: true,
            lowercase: true,
            trim: true,
            unique: true, // Ensure slugs are unique across the entire collection now
            index: true,
        },
        category: {
            type: String,
            required: true,
            lowercase: true,
            trim: true,
            index: true, // Index for faster filtering by category
        },
        subCategory: {
            type: String,
            trim: true,
        },
        summary: {
            type: String,
            trim: true,
            maxlength: 500,
        },
        content: {
            type: String,
            required: true,
            trim: true,
        },
        image: {
            type: String,
            default: null,
        },
        tags: [
            {
                type: String,
                trim: true,
            },
        ],
        isLatest: { type: Boolean, default: false },
        isTrending: { type: Boolean, default: false },
        isHidden: { type: Boolean, default: false },
        targetLink: { type: String, trim: true, default: null },
        urlHash: { type: String, trim: true, index: true, unique: true, sparse: true },
        nominationLink: { type: String, trim: true, default: null },
        moreInfoLink: { type: String, trim: true, default: null },
        author: { type: String, trim: true, default: "Prime Time News" },
        authorId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },
        status: {
            type: String,
            enum: ["draft", "published", "archived", "scheduled"],
            default: "draft",
            index: true,
        },
        scheduledAt: {
            type: Date,
            default: null,
            index: true,
        },
        autoGenerated: {
            type: Boolean,
            default: false,
        },
        source: {
            type: String,
            trim: true,
        },
        publishedAt: {
            type: Date,
            default: null,
        },
    },
    {
        timestamps: true,
    }
);

// Compound index for efficient querying
newsArticleSchema.index({ category: 1, status: 1, createdAt: -1 });
newsArticleSchema.index({ publishedAt: -1, createdAt: -1 });
newsArticleSchema.index({ status: 1, publishedAt: -1 });

// Full text search index
newsArticleSchema.index(
    {
        title: "text",
        summary: "text",
        content: "text",
        tags: "text",
    },
    {
        weights: {
            title: 10,
            tags: 8,
            summary: 5,
            content: 1,
        },
        name: "NewsTextSearchIndex",
    }
);

const NewsArticle = mongoose.models.NewsArticle || mongoose.model("NewsArticle", newsArticleSchema);

module.exports = NewsArticle;
