const mongoose = require("mongoose");

const newsArticleSchema = new mongoose.Schema(
    {
        title: {
            type: String,
            required: true,
            trim: true,
            minlength: 5,
            maxlength: 300,
        },
        slug: {
            type: String,
            required: true,
            lowercase: true,
            trim: true,
            unique: true, // Ensure slugs are unique across the entire collection now
            index: true,
        },
        category: {
            type: String,
            required: true,
            lowercase: true,
            trim: true,
            index: true, // Index for faster filtering by category
        },
        subCategory: {
            type: String,
            trim: true,
        },
        summary: {
            type: String,
            trim: true,
            maxlength: 500,
        },
        content: {
            type: String,
            required: true,
            trim: true,
        },
        image: {
            type: String,
            default: null,
        },
        tags: [
            {
                type: String,
                trim: true,
            },
        ],
        isLatest: { type: Boolean, default: false },
        isTrending: { type: Boolean, default: false },
        isHidden: { type: Boolean, default: false },
        targetLink: { type: String, trim: true, default: null },
        nominationLink: { type: String, trim: true, default: null },
        author: { type: String, trim: true, default: "Prime Time News" },
        authorId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },
        status: {
            type: String,
            enum: ["draft", "published", "archived"],
            default: "draft",
            index: true,
        },
        autoGenerated: {
            type: Boolean,
            default: false,
        },
        source: {
            type: String,
            trim: true,
        },
        publishedAt: {
            type: Date,
            default: null,
        },
    },
    {
        timestamps: true,
    }
);

// Compound index for efficient querying
newsArticleSchema.index({ category: 1, status: 1, createdAt: -1 });

const NewsArticle = mongoose.models.NewsArticle || mongoose.model("NewsArticle", newsArticleSchema);

module.exports = NewsArticle;
