import { baseURL } from "@/Utils/Utils";

export interface NewsItem {
    title: string;
    slug: string;
    category: string;
    subCategory?: string;
    summary?: string;
    content: string;
    image?: string;
    tags: string[];
    status: "draft" | "published" | "archived";
    publishedAt?: string;
    date?: string;
    isLatest?: boolean;
    isTrending?: boolean;
    isHidden?: boolean;
    isOpinion?: boolean;
    targetLink?: string;
    nominationLink?: string;
    author?: string;
    authorId?: string | {
        _id: string;
        name: string;
        ProfilePicture: string;
        designation: string;
    };
    _id?: string;
    section?: string;
    source?: string;
    autoGenerated?: boolean;
}


export interface NewsSections {
    india?: NewsItem[];
    sports?: NewsItem[];
    business?: NewsItem[];
    lifestyle?: NewsItem[];
    entertainment?: NewsItem[];
    health?: NewsItem[];
    awards?: NewsItem[];
    technology?: NewsItem[];
    world?: NewsItem[];
    education?: NewsItem[];
    environment?: NewsItem[];
    science?: NewsItem[];
    opinion?: NewsItem[];
    auto?: NewsItem[];
    travel?: NewsItem[];
    state?: NewsItem[];
}

export interface NewsDocument extends NewsSections {
    _id?: string;
    isActive?: boolean;
    lastUpdated?: string;
}

export interface ApiResponse<T = unknown> {
    success: boolean;
    news?: T;
    data?: T;
    msg: string;
    count?: number;
    pagination?: {
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    };
    total?: number;
}

class NewsService {
    private async request<T>(endpoint: string, options: RequestInit = {}): Promise<ApiResponse<T>> {
        const url = `${baseURL}/news${endpoint}`;

        // Add default revalidation for GET requests
        const isGet = !options.method || options.method === 'GET';
        const fetchOptions: RequestInit = {
            headers: { "Content-Type": "application/json" },
            ...options,
            next: isGet ? { revalidate: 60, tags: ['news'] } : options.next
        };

        const res = await fetch(url, fetchOptions);
        if (!res.ok) {
            const errorData = await res.json().catch(() => ({}));
            throw new Error(errorData.msg || `API Error: ${res.status}`);
        }
        return res.json();
    }

    addNews = (news: Omit<NewsItem, "id"> & { section: string }): Promise<ApiResponse<NewsItem>> =>
        this.request("/addnews", { method: "POST", body: JSON.stringify(news) });

    getAllNews = (includeDrafts: boolean = false, page: number = 1, limit: number = 10): Promise<ApiResponse<NewsItem[]>> => {
        const endpoint = `/getallnews?page=${page}&limit=${limit}${includeDrafts ? '&includeDrafts=true' : ''}`;
        return this.request(endpoint);
    };

    getNewsBySection = (section: string, includeDrafts: boolean = false, page: number = 1, limit: number = 10): Promise<ApiResponse<NewsItem[]>> => {
        const endpoint = `/getnewsbysection/${section}?page=${page}&limit=${limit}${includeDrafts ? '&includeDrafts=true' : ''}`;
        return this.request(endpoint);
    };

    getNewsBySlug = (section: string, slug: string, includeDrafts: boolean = false): Promise<ApiResponse<NewsItem>> => {
        const endpoint = `/getnewsbyslug/${section}/${slug}${includeDrafts ? '?includeDrafts=true' : ''}`;
        return this.request(endpoint);
    };

    updateNews = (params: { section: string; slug: string; data: Partial<NewsItem> }): Promise<ApiResponse<NewsItem>> =>
        this.request(`/updatenews/${params.section}/${params.slug}`, {
            method: "PUT",
            body: JSON.stringify(params.data),
        });

    deleteNews = (params: { section: string; slug: string }): Promise<ApiResponse<{ deleted: boolean }>> =>
        this.request(`/deletenews/${params.section}/${params.slug}`, { method: "DELETE" });

    setNewsFlags = (params: {
        section: string;
        slug: string;
        flags: Partial<Pick<NewsItem, "isLatest" | "isTrending" | "isHidden">>;
    }): Promise<ApiResponse<NewsItem>> =>
        this.request(`/flags/${params.section}/${params.slug}`, {
            method: "PATCH",
            body: JSON.stringify(params.flags),
        });

    searchNews = (query: string, page: number = 1, limit: number = 10): Promise<ApiResponse<NewsItem[]>> => {
        const endpoint = `/search?q=${encodeURIComponent(query)}&page=${page}&limit=${limit}`;
        return this.request(endpoint);
    };
}

export const newsService = new NewsService();
